# Funding

You can support the development of the Boarding House Management System through:

github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON
# open_collective: YOUR_COLLECTIVE
# ko_fi: YOUR_KO_FI
# custom: ['https://your-custom-link.com']
