# Configuration for the labeler action

# Documentation changes
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - '.github/**/*.md'

# Database changes
database:
  - 'packages/database/**/*'
  - '**/*.prisma'
  - '**/migrations/**/*'

# API changes
api:
  - 'apps/api/**/*'
  - 'packages/api/**/*'

# Frontend changes
frontend:
  - 'apps/(public)/**/*'
  - 'apps/boarder/**/*'
  - 'apps/landlord/**/*'
  - 'apps/(auth)/**/*'

# Admin changes
admin:
  - 'apps/admin/**/*'

# Mobile changes
mobile:
  - 'apps/mobile/**/*'

# UI/Components changes
ui:
  - 'packages/ui/**/*'
  - '**/*.tsx'
  - '**/*.jsx'

# Authentication changes
auth:
  - 'packages/auth/**/*'
  - '**/auth/**/*'

# Configuration changes
config:
  - 'packages/config/**/*'
  - '**/*.config.*'
  - '**/tsconfig.json'
  - '**/package.json'
  - 'turbo.json'

# CI/CD changes
ci:
  - '.github/workflows/**/*'
  - '.github/actions/**/*'

# Dependencies
dependencies:
  - 'package.json'
  - 'bun.lock'
  - '**/package.json'

# Tests
tests:
  - '**/*.test.*'
  - '**/*.spec.*'
  - '**/tests/**/*'
  - '**/__tests__/**/*'

# Docker
docker:
  - '**/Dockerfile'
  - '**/docker-compose*.yml'
  - '**/.dockerignore'

# Security
security:
  - '.github/dependabot.yml'
  - '**/security/**/*'