# Configuration for the labeler action (v5 format)

documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.md'
      - 'docs/**/*'
      - '.github/**/*.md'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/database/**/*'
      - '**/*.prisma'
      - '**/migrations/**/*'

api:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/api/**/*'
      - 'packages/api/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/(public)/**/*'
      - 'apps/boarder/**/*'
      - 'apps/landlord/**/*'
      - 'apps/(auth)/**/*'

admin:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/admin/**/*'

mobile:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/mobile/**/*'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/ui/**/*'
      - '**/*.tsx'
      - '**/*.jsx'

auth:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/auth/**/*'
      - '**/auth/**/*'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/config/**/*'
      - '**/*.config.*'
      - '**/tsconfig.json'
      - '**/package.json'
      - 'turbo.json'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/actions/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'bun.lock'
      - '**/package.json'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.*'
      - '**/*.spec.*'
      - '**/tests/**/*'
      - '**/__tests__/**/*'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '**/.dockerignore'

security:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/dependabot.yml'
      - '**/security/**/*'